; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:4d_systems_esp32s3_gen4_r8n16]
; platform = espressif32
; board = 4d_systems_esp32s3_gen4_r8n16
; framework = arduino

# https://github.com/KrisKasprzak/ESP32_WebPage/blob/main/WebPageUpdate.ino

[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    bblanchon/ArduinoJson@^6.21.0
    ottowinter/ESPAsyncWebServer-esphome @ ^3.0.0
    # For ESP32:
    me-no-dev/AsyncTCP @ ^1.1.1


; CREATING A NEW PROJECT

; 1. Select 4D Systems GEN4-ESP32 16MB (ESP32S3-R8N16)
    ; Framework: Arduino

; 2. Create Folder 'borads' in the roject's root 
    ; and create file 'esp32-s3-devkitc-1-n16r8v.json'

; 3. Copy and paste from here or https://github.com/handledexception/platform-espressif32/commit/deb6aa342245ad7bcb3d9ed69050f203779833ab

; 4. In the platformio.ini file, copy the properties from here
        ; [env:esp32-s3-devkitc-1-n16r8v]
        ; platform = espressif32
        ; board = esp32-s3-devkitc-1-n16r8v
        ; framework = arduino
        ; build_flags = 
        ;     -D ARDUINO_USB_CDC_ON_BOOT=1
        ; monitor_speed = 115200

; 5. To view the Serial Monitor, be sure to use Serial.begin(921600);
     ; If you check esp32-s3-devkitc-1-n16r8v.json, the speed is set at "speed": 921600

; 6. Add this to view serial monitor correctly
;       Serial.begin(115200);
;       delay(500);



; ERROR 1 BUILD
; ERROR message : platformio from intelhex import HexRecordError, IntelHexModuleNotFoundError: No module named 'intelhex'

; SOLUTION :
; 1. Close your VS Code or PlatformIO IDE completely.
; 2. Navigate to /home/abemonty/.platformio/packages
; 3. Delete the tool-esptoolpy folder within the packages directory.